### PR TITLE
Add the 'prev' and 'next' post title tooltip preview.

### PR DESCRIPTION
**Pull request by quentin-chen**
Demo can be seen here: [Demo](http://kchen.cc/2016/11/17/iterm2-and-tmux-integration/)

### CODE REVIEW

**Comment by quentin-chen** [comment]
#58

**Comment by ahonn** [comment]
Doesn't look like the "even" theme style. 
Maybe change the 'next' or 'prev' text will be better

**Comment by quentin-chen** [comment]
So you mean there is no need to show up a tooltip but change the 'prev' to the tile of that post when the mouse move over on it?

**Comment by quentin-chen** [comment]
It seems that you have the better theme style.

**Pull request closed without merging**
